# Generated by Django 4.1.7 on 2023-04-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_de_Album', '0002_rename_ano_do_lancamento_album_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
