# Generated by Django 4.1.7 on 2023-04-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_de_Album', '0004_cliente_email_loja_numero_alter_album_lancamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loja',
            old_name='numero',
            new_name='tel_para_contato',
        ),
    ]
