# Generated by Django 4.1.7 on 2023-04-01 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loja_de_Album', '0005_rename_numero_loja_tel_para_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='endereco',
            new_name='endereco_de_residencia',
        ),
    ]
